version: '3'

services:

  backend:
    build: ./recomendador-backend/recomendador-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./recomendador-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend